config/routes.rb
Showping::Application.routes.draw do
  
  devise_for :users 
  
  devise_for :admin_users, ActiveAdmin::Devise.config 
    ActiveAdmin.routes(self) do
      resources :requests
    end
  resources :users do
    resources :requests do
      resources :comments
    end
  end
  
  resources :comments
  
  resources :users do
    resources :profiles
  end
  
  match '/users/:user_id/my_profiles', to: 'profiles#my_profiles', via: 'get', as: 'my_profiles' 
  
  resources :profiles do
      resources :requests do 
        get 'new_product', on: :new
        get 'new_service', on: :new 
        get 'new_event', on: :new       
        resources :comments
      end
  end
  
  
  
  namespace :admin do
    resources :profiles do
      resources :requests
    end
  end
  namespace :admin do
    resources :users do
      resources :requests
    end    
  end
  
  namespace :admin do
    resources :requests do
      resources :comments
    end  
  end
   
  resources :requests do
    resources :comments
  end
  
  match '/contact_form', to: 'contact_form#new', via: 'get'
  match '/send_email', to: 'contact_form#send_email', via: 'post'

  root to: "profiles#index"
  

  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  
  has_many :requests  
  belongs_to :user  
  #has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "250x250>" }, :default_url => "/images/:style/No_Image.png"
  paginates_per 50
  
  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :image, styles: {
    thumb: '100x100#',
    square: '1024x680>',
    medium: '300x300#'
  },
  :default_url => "/images/:style/No_Image.png"
  #:s3_credentials => S3_CREDENTIALS,
  #:storage => :s3,
  

  
  #searchable do
    #text :name, :profession, :latitude, :longitude    
  #end
  
  geocoded_by :current_location
  after_validation :geocode, :if => :current_location_changed?
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  
  before_action :owns_profile, only: [:edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def my_profiles
    @user = User.find(params[:user_id])
    @profiles = @user.profiles
  end
  
  
  def index
    #@search = Profile.search do
      #fulltext params[:search]
    #end
    #@profiles = Profile.all 
    if params[:locate].present?
      @search = Profile.near(params[:locate], 50).search(params[:q])      
    else
      @search = Profile.search(params[:q])
    end
    
    @profiles = @search.result.page(params[:page]).per(10)
      
    #@search = Profile.search(params[:q]) 
    #@profiles = @search.result(distinct: true).order("name").page(params[:page], per_page => 10)
    #@profiles = Profile.near(params[:search], 50).search(params[:search]).relation.paginate(:page => params[:page], :per_page => 9)
    #@profiles = @search.result
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new    
    @user = current_user
    @profile = Profile.new(:user_id => @user.id)
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = current_user.profiles.build(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

  private
    
    def owns_profile
      #if !user_signed_in? || current_user != Profile.find(params[:id]).user
      if !user_signed_in? || current_user.profiles.find_by(id: params[:id]).nil?
        redirect_to profiles_path, error: "Cannot modify profiles you don't own"
      end
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:description, :experience, :profession, :current_location,
       :user_id, :image, :youtube_url, :name, :latitude, :longitude)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def youtube_embed(youtube_url)
  if youtube_url[/youtu\.be\/([^\?]*)/]
    youtube_id = $1
    else
      # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
      youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end

  %Q{<iframe title="YouTube video player" width="100%" height="500" src="http://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
  end
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  
  <%= f.error_notification %>   
  <%= f.input :name %>
  <%= f.input :description, label: 'Info' %>
  <%= f.input :experience, label: 'Years of Experience' %>
  <%= f.input :profession %>
  <%= f.input :current_location %>  
  <%= f.input :image %>
  <%= f.input :youtube_url %>	
	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<!-- button type="button" class="btn-mini btn-success" data-toggle="collapse" data-target="#search"> Open/Close Search </button> -->
<h1></h1>
<table class="table span12">
  <thead>
    <tr>
      <th></th>      
      <th><%= sort_link @search, :name, "Name" %></th>      
      <th><%= sort_link @search, :experience, "Experience (years)" %></th>
      <th>Profession</th>
      <th>Location</th>
      <th>$$$</th>      
    </tr>
  </thead>
  
   <div id="search" data-spy="affix-top" data-offset-top="20" class="collapse in form-search form-inline" >
  <%= search_form_for @search do |f|%>
  <div class="row">
  	<div class="span3">
  		<%= f.text_field :profession_cont, {:class => "input-medium search-query", :placeholder => "Search by Profession"} %>
  	</div>
  	<div class="span3">
    <!-- <%= text_field_tag :search, params[:search] %> -->
    <!-- <%= f.label :name_cont, " ." %> -->
    	<%= f.text_field :name_cont, {:class => "input-medium search-query", :placeholder => "Search By Name"} %>
    </div>
    <div class="span3>
	    <%= label_tag :_ %> 
	    <%= text_field_tag :locate, params[:locate], {:class => "input-medium search-query", :placeholder => "Search By City" } %> 
    </div>
    <div class="span3">
    	<%= f.submit "Search", {:class => "btn " } %> 
    </div>
   <% end %>
   </div>
  
   	
 <br></br>
 <%= paginate @profiles %> 

  <tbody>
  	<div class="container-fluid media">
  		<div class="row-fluid">
  			<div class="span4">
		    <% @profiles.each do |profile| %>
		      <tr>
		      	
		      	<td class="thumbnails visible-tablet visible-desktop hidden-phone"><%= link_to (image_tag profile.image.url(:medium)), profile %></td>
		      	<td class="thumbnails hidden-tablet hidden-desktop visible-phone"><%= link_to (image_tag profile.image.url(:thumb)), profile %></td>        
		        <td><%= profile.name %></td>        
		        <td><%= profile.experience %></td>
		        <td><%= profile.profession %></td>
		        <td><%= profile.current_location %></td>	        
		        
		      </tr>
		    <% end %>
		</div>
	  </div>
	</div>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/my_profiles.html.erb
<h1></h1>
<table class="table span12">
  <thead>
    <tr>
      <th></th>      
      <th>Name</th>      
      <th>Experience</th>
      <th>Profession</th>
      <th>Location</th>           
    </tr>
  </thead>
   	
 <br></br>
 
  <tbody>
  	<div class="container-fluid media">
  		<div class="row-fluid">
  			<div class="span4">
		    <% @profiles.each do |profile| %>
		      <tr>		      	
		      	<td class="thumbnails visible-tablet visible-desktop hidden-phone"><%= link_to (image_tag profile.image.url(:medium)), profile %></td>
		      	<td class="thumbnails hidden-tablet hidden-desktop visible-phone"><%= link_to (image_tag profile.image.url(:thumb)), profile %></td>        
		        <td><%= profile.name %></td>        
		        <td><%= profile.experience %></td>
		        <td><%= profile.profession %></td>
		        <td><%= profile.current_location %></td> 
		      </tr>
		    <% end %>
		</div>
	  </div>
	</div>
  </tbody>
</table>

<br>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div class="text-center">
<% if user_signed_in? && current_user == @profile.user %>
<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>
<%end%>
</div>

<table class="container-fluid">
  <div class="row-fluid">	
     <div class="span6">
		<p class="lead text-center">	  
		  <strong><%= @profile.name %></strong> <br />		      
		</p>
		
		<div style="padding-right: 30px;">	
			<p class="lead text-center">
			<%= image_tag @profile.image.url(:square), :class => "img-polaroid" %>
			</p>
		</div>		
	  </div>	
	<!--<%= image_tag @profile.image.url(:medium) %>-->
	<!--<%= image_tag @profile.image.url(:thumb) %>-->
		<br ></br>
		<div class="span6 btn-group">
			<% if user_signed_in? && current_user != @profile.user %>
				<p class="lead text-left">
				<%= button_to "Make a Wish!", new_profile_request_path(@profile), :class => "btn btn-large btn-block btn-primary", :type => "button", :method => "get" %>  
				</p>
		    <%else%>
			<a class="btn dropdown-toggle btn-large btn-primary" data-toggle="dropdown" href="#"> New Offering <span class="caret"></span> </a>		
			<ul class="dropdown-menu btn-primary">
			<li><%= button_to "Product", new_product_new_profile_request_path(@profile), :class => "btn btn-large btn-block btn-primary", :type => "button", :method => "get" %></li>
			<li><%= button_to "Service", new_service_new_profile_request_path(@profile), :class => "btn btn-large btn-block btn-primary", :type => "button", :method => "get" %> </li>
			<li><%= button_to "Event", new_event_new_profile_request_path(@profile), :class => "btn btn-large btn-block btn-primary", :type => "button", :method => "get" %></li>
			<li role="presentation" class="divider"></li>
			<li><%= button_to "Basic", new_profile_request_path(@profile), :class => "btn btn-large btn-block btn-primary", :type => "button", :method => "get" %></li>
			<%end%>
		</div>
		<br ></br>
		<br ></br>			
<!--		<% if user_signed_in? && current_user == @profile.user %>
			<p class="lead text-left">
			<%= button_to "Create New Product", new_product_new_profile_request_path(@profile), :class => "btn btn-large btn-block btn-primary", :type => "button", :method => "get" %>  
			</p>
			<p class="lead text-left">
			<%= button_to "Create New Service", new_service_new_profile_request_path(@profile), :class => "btn btn-large btn-block btn-primary", :type => "button", :method => "get" %>  
			</p>
			<p class="lead text-left">
			<%= button_to "Create New Event", new_event_new_profile_request_path(@profile), :class => "btn btn-large btn-block btn-primary", :type => "button", :method => "get" %>  
			</p>				
		<p ></p>	
		<%else%>
		<p class="lead text-left">
			<%= button_to "Make a Wish!", new_profile_request_path(@profile), :class => "btn btn-large btn-block btn-primary", :type => "button", :method => "get" %>  
		</p><p ></p>
		<%end%>
-->		<div class="span6">	
		<p class="lead text-left">
		  <strong>Experience:</strong>
		  <%= @profile.experience %>
		</p>
		
		<p class="lead text-left">	
		  <strong>Profession:</strong>
		  <%= @profile.profession %>	
		</p>	
		
		<p class="lead text-left">
		  <strong>Current location:</strong>
		  <%= @profile.current_location %>
		</p>
		
		</div>
	
	
	<div class="span12">
		<p class="lead text-left">
		  <strong>About:   </strong>
		  <%= @profile.description %>
		</p>
	</div>

	<br />	
	</div>
</table>	
  

<p class="text-center">  
  <strong><%= link_to 'Make a Wish', new_profile_request_path(@profile) %></strong>
</p>
	<br /> 
	
	<table class="table table-striped">
	<tr>
		<th>Request</th>		
		<th>Date</th>
		<th>Time</th>
		<th>Description</th>
	</tr>  
 
	<% @profile.requests.each do |request| %>
	<% if user_signed_in? && (current_user == request.user || current_user == @profile.user) %>
	
	  	<tr>
	  	<td><%= link_to 'View Wish', profile_request_path(@profile, request)%></td>
	  	<td><%= request.date.strftime("%B %d, %Y") %></td>
	  	<td><%= request.time.strftime("%I:%M %p")%></td>
	  	<td><%= request.description %></td>
	  </tr>
	  <% end %>  
	<% end %>
  </table>
</body>