config/routes.rb
Showping::Application.routes.draw do
  
  devise_for :users 
  
  devise_for :admin_users, ActiveAdmin::Devise.config 
    ActiveAdmin.routes(self) do
      resources :requests
    end
  resources :users do
    resources :requests do
      resources :comments
    end
  end
  
  resources :comments
  
  resources :users do
    resources :profiles
  end
  
  match '/users/:user_id/my_profiles', to: 'profiles#my_profiles', via: 'get', as: 'my_profiles' 
  
  resources :profiles do
      resources :requests do 
        get 'new_product', on: :new
        get 'new_service', on: :new 
        get 'new_event', on: :new       
        resources :comments
      end
  end
  
  
  
  namespace :admin do
    resources :profiles do
      resources :requests
    end
  end
  namespace :admin do
    resources :users do
      resources :requests
    end    
  end
  
  namespace :admin do
    resources :requests do
      resources :comments
    end  
  end
   
  resources :requests do
    resources :comments
  end
  
  match '/contact_form', to: 'contact_form#new', via: 'get'
  match '/send_email', to: 'contact_form#send_email', via: 'post'

  root to: "profiles#index"
  

  

end

app/controllers/contact_form_controller.rb
class ContactFormController< ApplicationController
  
  
  def new
    @contact_form = ContactForm.new
  end
  
  def send_email
    @contact_form = ContactForm.new(params[:contact_form])
    if @contact_form.valid?
      ContactMailer.contact_us(@contact_form, @contact_form.note).deliver
      redirect_to root_path, :notice => "Thank you! Your message was sent successfully. We will contact you shortly."
    else
      flash.now[:error] = "Hmm. We couldn't send your message. Please double check the fields and make sure the form is filled out correctly."
      render :new
    end
  end
end

app/views/contact_form/new.html.erb
<h1>Contact Us</h1>

<%=form_for @contact_form,:url => send_email_path do |f| %>
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %><br />
	</div>
	
	<div class="field">
		<%= f.label :email %>
		<%= f.text_field :email %><br />
	</div>
	
	<div class="field">
		<%= f.label :note %>
		<%= f.text_area :note %><br />
	</div>
	
	<br />
	
	<div class="">		
		<%= f.submit 'Send', :class => 'btn' %>
	</div>
<% end %>