config/routes.rb
Showping::Application.routes.draw do
  
  devise_for :users 
  
  devise_for :admin_users, ActiveAdmin::Devise.config 
    ActiveAdmin.routes(self) do
      resources :requests
    end
  resources :users do
    resources :requests do
      resources :comments
    end
  end
  
  resources :comments
  
  resources :users do
    resources :profiles
  end
  
  match '/users/:user_id/my_profiles', to: 'profiles#my_profiles', via: 'get', as: 'my_profiles' 
  
  resources :profiles do
      resources :requests do 
        get 'new_product', on: :new
        get 'new_service', on: :new 
        get 'new_event', on: :new       
        resources :comments
      end
  end
  
  
  
  namespace :admin do
    resources :profiles do
      resources :requests
    end
  end
  namespace :admin do
    resources :users do
      resources :requests
    end    
  end
  
  namespace :admin do
    resources :requests do
      resources :comments
    end  
  end
   
  resources :requests do
    resources :comments
  end
  
  match '/contact_form', to: 'contact_form#new', via: 'get'
  match '/send_email', to: 'contact_form#send_email', via: 'post'

  root to: "profiles#index"
  

  

end

app/models/request.rb
class Request < ActiveRecord::Base
  paginates_per 10  
  belongs_to :user  
  belongs_to :profile
  acts_as_commentable
  
  before_create :type_designation
  #has_many :comments, as: :commentable
  #has_one :profile 
  
  #attr_accessible :description, :profile, :user
  
  #validates_presence_of :description
  validates :price, :numericality => {:less_than => 10000.00}
  
  private
  
  def type_designation
    if self.user == self.profile.user
      self.offering = true
    end
  end
  
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]  
  before_action :owns_request, only: [:edit, :update, :destroy]  
  
  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    #@profile = Profile.find(params[:profile_id])
    @user = current_user
    @request = Request.find(params[:id])
  #enable comments
    @commentable = @request
    @comments = @commentable.comments
    @comment = Comment.new
  end
  # GET /requests/new
  def new
    @user = current_user
    @profile = Profile.find(params[:profile_id])
    @request = Request.new(:user_id => @user) 
    @request.record_type = 'wish'    
  end
  
  def new_product
    @user = current_user
    @profile = Profile.find(params[:profile_id])
    @request = Request.new(:user_id => @user) 
    @request.record_type = 'product'      
  end
  
  def new_service
    @user = current_user
    @profile = Profile.find(params[:profile_id])
    @request = Request.new(:user_id => @user)
    @request.record_type = 'service'      
  end
  
  def new_event
    @user = current_user
    @profile = Profile.find(params[:profile_id])
    @request = Request.new(:user_id => @user) 
    @request.record_type = 'event'    
  end

  # GET /requests/1/edit
  def edit
    @profile = Profile.find(params[:profile_id])    
    
    #@request = Request.find(request_params)    
  end
  
  # POST /requests
  # POST /requests.json
  def create    
    @profile = Profile.find(params[:profile_id])
    @user = current_user
    @request = @user.requests.build(request_params)
    @request.profile = @profile
   

    respond_to do |format|
      if @request.save
        format.html { redirect_to profile_request_path(@profile, @request), notice: 'Request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @request }
      else
        format.html { render action: 'new' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)       
        #format.html { redirect_to profile_request_path(@request.profile, @request), notice: 'Request was successfully updated.' }
        format.html { redirect_to profile_request_path(@profile, @request), notice: 'Request was successfully updated.'}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end

  private
  
    def owns_request
       @profile = Profile.find(params[:profile_id])
      #if !user_signed_in? || current_user != Profile.find(params[:id]).user
      if !user_signed_in? || current_user.requests.find_by(id: params[:id]).nil? 
        redirect_to requests_path, error: "Cannot modify requests you don't own" 
      end
    end    
  
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end   

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:date, :time, :description, :profile_id, :user_id, :price, :payment_date, :offering, :name, :limit, :amount, :record_type)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= simple_form_for([@profile, @request]) do |f| %>
   <!-- %= f.inputs :name => "Advanced" do 
	 %= f.error_notification % 
	   f.input :profile, :value => Profile.find(params[:profile_id]).id 
	  < f.input :user, :value => current_user.id
	  end % -->	 
	  
	<%= f.error_notification %>
	 
	  <%= f.input :date, as: :string, :id => "datepicker col-span-3", input_html: { class: "datepicker", value: Time.zone.now.to_date.strftime('%m/%d/%Y')}%>
		  
	  <%= f.input :time, as: :time, :minute_step => 15, :ampm => true, input_html: { class: "dateselect-time input-small", value: Time.zone.now.utc.strftime("%I:%M %p")} %>
	       <!-- f.input :time, :as => :time_picker  "use this for formtastic"-->
      
	  <%= f.input :description %>
	  
	  <%= f.input :price %>
  <br></br> 
  
  <div class="">
    <%= f.submit 'Save', :class => 'btn' %>
  </div>
<% end %>

app/views/requests/_form_event.html.erb
<%= simple_form_for([@profile, @request]) do |f| %>
   <!-- %= f.inputs :name => "Advanced" do 
	 %= f.error_notification % 
	   f.input :profile, :value => Profile.find(params[:profile_id]).id 
	  < f.input :user, :value => current_user.id
	  end % -->	 
	  
	<%= f.error_notification %>
	  <%= f.input :name %>
	  <%= f.input :date, as: :string, :id => "datepicker col-span-3", label: "Delivery Date", input_html: { class: "datepicker", value: Time.zone.now.to_date.strftime('%m/%d/%Y')}%>		  
	  <%= f.input :time, as: :time, :minute_step => 15, :ampm => true, input_html: { class: "dateselect-time input-small", value: Time.zone.now.utc.strftime("%I:%M %p")} %>
	       <!-- f.input :time, :as => :time_picker  "use this for formtastic"-->
	  <%= f.input :limit %>      
	  <%= f.input :description %>	  
	  <%= f.input :price %>
	  <%= f.hidden_field :record_type %>
  <br></br> 
  
  <div class="">
    <%= f.submit 'Save', :class => 'btn' %>
  </div>
<% end %>

app/views/requests/_form_product.html.erb
<%= simple_form_for([@profile, @request]) do |f| %>
   <!-- %= f.inputs :name => "Advanced" do 
	 %= f.error_notification % 
	   f.input :profile, :value => Profile.find(params[:profile_id]).id 
	  < f.input :user, :value => current_user.id
	  end % -->	 
	  
	<%= f.error_notification %>
	  <%= f.input :name %>
	  <%= f.input :date, as: :string, :id => "datepicker col-span-3", label: "Delivery Date", input_html: { class: "datepicker", value: Time.zone.now.to_date.strftime('%m/%d/%Y')}%>		  
	  <%= f.input :time, as: :time, :minute_step => 15, :ampm => true, input_html: { class: "dateselect-time input-small", value: Time.zone.now.utc.strftime("%I:%M %p")} %>
	       <!-- f.input :time, :as => :time_picker  "use this for formtastic"-->
	  <%= f.input :limit %>      
	  <%= f.input :description %>	  
	  <%= f.input :price %>
	  <%= f.hidden_field :record_type %>
  <br></br> 
  
  <div class="">
    <%= f.submit 'Save', :class => 'btn' %>
  </div>
<% end %>

app/views/requests/_form_service.html.erb
<%= simple_form_for([@profile, @request]) do |f| %>
   <!-- %= f.inputs :name => "Advanced" do 
	 %= f.error_notification % 
	   f.input :profile, :value => Profile.find(params[:profile_id]).id 
	  < f.input :user, :value => current_user.id
	  end % -->	 
	  
	<%= f.error_notification %>
	  <%= f.input :name %>
	  <%= f.input :date, as: :string, :id => "datepicker col-span-3", label: "Delivery Date", input_html: { class: "datepicker", value: Time.zone.now.to_date.strftime('%m/%d/%Y')}%>		  
	  <%= f.input :time, as: :time, :minute_step => 15, :ampm => true, input_html: { class: "dateselect-time input-small", value: Time.zone.now.utc.strftime("%I:%M %p")} %>
	       <!-- f.input :time, :as => :time_picker  "use this for formtastic"-->
	  <%= f.input :limit %>      
	  <%= f.input :description %>	  
	  <%= f.input :price %>
	  <%= f.hidden_field :record_type %>
  <br></br> 
  
  <div class="">
    <%= f.submit 'Save', :class => 'btn' %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<br></br>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1>My Wishes</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  	
    <% @requests.each do |request| %>
      <tr>
      <% if user_signed_in? && current_user == request.user %>
        <td><%= request.date.strftime("%B %d, %Y") %></td>
        <td><%= request.time.strftime("%I:%M %p") %></td>
        <td><%= request.description %></td>
      
        <td><%= link_to 'Show',  profile_request_path(request.profile_id, request) %></td>
        <td><%= link_to 'Edit', edit_profile_request_path(request.profile_id, request) %></td>
        <td><%= link_to 'Destroy', profile_request_path(request.profile_id, request), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %> 
      </tr>
    <% end %>
  
  </tbody>
</table>
</br> </br>

<h1>Wishes for Me</h1>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
      <% if user_signed_in? && current_user == request.profile.try(:user) %>
        <td><%= request.date.strftime("%B %d, %Y") %></td>
        <td><%= request.time.strftime("%I:%M %p") %></td>
        <td><%= request.description %></td>
      
        <td><%= link_to 'Show',  profile_request_path(request.profile_id, request) %></td>        
      <% end %> 
      </tr>
    <% end %>
  </tbody>
</table>

app/views/requests/new.html.erb
<% if user_signed_in? && current_user != @profile.user %>
<h1>New Wish</h1>
<%= render 'form' %>
<%else%>
<h1>New Offering</h1>
<%= render 'form' %>
<% end %>
<%= link_to 'Back', requests_path %>

app/views/requests/new_event.html.erb
<h1>New Event Offering</h1>
<%= render 'form_event' %>
<%= link_to 'Back', requests_path %>

app/views/requests/new_product.html.erb
<h1>New Product Offering</h1>
<%= render 'form_product' %>
<%= link_to 'Back', requests_path %>

app/views/requests/new_service.html.erb
<h1>New Service Offering</h1>
<%= render 'form_service' %>
<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<% if user_signed_in? && current_user == @request.user %>
<%= link_to 'Edit', edit_profile_request_path(@request.profile_id, @request) %> 
<%= link_to 'Back', profile_path(@request.profile_id) %>
<%end%>
<br></br>

<p>
  <strong>Date:</strong>
  <%= @request.date.strftime("%B %d, %Y") %> 

  <strong>Time:</strong>
  <%= @request.time.strftime("%I:%M %p") %>
</p>

<p>
  <strong>Description:</strong>
  <%= @request.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@request.price, precision: 2) %>
</p>

<p>
  <strong>Offering:</strong>
  <%= @request.offering %>
</p>
<p>
  <strong>Type:</strong>
  <%= @request.record_type %>
</p>
<p>
</p>
<p>
  <small>Created At:
  <%= @request.created_at.in_time_zone(Time.zone).strftime("%B %d, %Y"" at " "%I:%M %p") %>
  </small>
</p>


<h1>...</h1>
<p>
</p>
<% if user_signed_in? && (current_user == @comment.user || current_user == @commentable.profile.user || current_user == @commentable.user) %>
<%= render "comments/comments" %>
<%= render "comments/form" %>
<% end %>