config/routes.rb
Showping::Application.routes.draw do
  
  devise_for :users 
  
  devise_for :admin_users, ActiveAdmin::Devise.config 
    ActiveAdmin.routes(self) do
      resources :requests
    end
  resources :users do
    resources :requests do
      resources :comments
    end
  end
  
  resources :comments
  
  resources :users do
    resources :profiles
  end
  
  match '/users/:user_id/my_profiles', to: 'profiles#my_profiles', via: 'get', as: 'my_profiles' 
  
  resources :profiles do
      resources :requests do 
        get 'new_product', on: :new
        get 'new_service', on: :new 
        get 'new_event', on: :new       
        resources :comments
      end
  end
  
  
  
  namespace :admin do
    resources :profiles do
      resources :requests
    end
  end
  namespace :admin do
    resources :users do
      resources :requests
    end    
  end
  
  namespace :admin do
    resources :requests do
      resources :comments
    end  
  end
   
  resources :requests do
    resources :comments
  end
  
  match '/contact_form', to: 'contact_form#new', via: 'get'
  match '/send_email', to: 'contact_form#send_email', via: 'post'

  root to: "profiles#index"
  

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" >
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "virthium" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "bootstrap_and_overrides", :media => "all" %>
    
     

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>    
     
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          	<a class="btn btn-navbar pull-right" data-target=".nav-collapse" data-toggle="collapse"> 
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>            
          </a>
          <a class="brand" href="/">virthium</a>
          <div class="container nav-collapse">
          	
            <ul class="nav">				
				<% if user_signed_in? && current_user.profiles.any?%>				
                <li><%= link_to "My Profiles", my_profiles_path(current_user) %></li>
                <% end %>
                
                <% if user_signed_in? && current_user.profiles.any?%>	
                <li><%= link_to "Requests", user_requests_path(current_user)%></li>
                <% end %>
            </ul>  
              
             <ul class="nav pull-right">	   
                <% if user_signed_in? %>                 					  
				  <li><%= link_to current_user.first_name, edit_user_registration_path %> </li>
				  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>	
				<% else %>
						
				  <li><%= link_to "Sign up", new_user_registration_path %> </li>
				  <li><%= link_to "Login", new_user_session_path %></li>
				<% end %>                	            
            </ul>
            
          </div><!--/.nav-collapse -->
        </div> 
      </div>
    </div>    
    
  <!--  
     <% if user_signed_in? %>
    	<div class="span2">
            <div class="well sidebar-nav" >
              <h3>Sidebar</h3>
              <ul class="nav nav-justified">
                <li class="nav-header"></li>
                <% if user_signed_in? && current_user.profiles.any?%>				
                <li><%= link_to "Profiles", user_profiles_path(current_user) %></li>
                <li><%= link_to "Requests", user_requests_path(current_user)%></li>
                <% end %>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well --
          </div><!--/span--
    <% end %>
 -->    
    
  <div class="container-fluid">
	<% flash.each do |name, msg| %>
	  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
	    <a class="close" data-dismiss="alert" href="">&times;</a>
	    <%= msg %>
	  </div>
	<% end %>
    <div class="table">
        <div class="row">
          <div class="container-fluid">            
            <%= yield %>
          </div>
          
          
        </div><!--/row-->
	  </div><!--/container-->
      <footer>
        <p>&copy; virthium 2014   <%= button_to "Contact Us", contact_form_path , :class => "btn btn-info", :type => "button", :method => "get" %></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster --> 
    
    <%= javascript_include_tag "application" %>
 <!--   <%= javascript_include_tag "bootstrap-collapse.js" %> --> 
    
   

  </body>
</html>